@startuml
skinparam handwritten true
skinparam backgroundcolor transparent
skinparam actor {
    BackgroundColor White
    BorderColor Black
}

actor "Persona 1" as P1
actor "Persona 2" as P2

P1 -right- P2 : "se toman de la mano"
@enduml